id: P009657
initial_creation_type: ocr
source_metadata:
  id: bdr:W21512
  title: འབྲུག་པ་དཀར་བརྒྱུད་པའི་དབང་དཔེ
  author: ''
  volumes:
    2ac76fce65d146cd83abf057c5b9d027:
      image_group_id: I0842
      title: ''
      volume_number: 1
      total_pages: 514
