id: P009657
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:43:10.594335
source_metadata:
  id: bdr:W21512
  title: འབྲུག་པ་དཀར་བརྒྱུད་པའི་དབང་དཔེ
  author: ''
  volumes:
    2ac76fce65d146cd83abf057c5b9d027:
      image_group_id: I0842
      title: ''
      volume_number: 1
      total_pages: 514
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
