id: IB2120205
legacy_id: P009657
ocr_import_info:
  bdrc_scan_id: W21512
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:38:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:11:48.677932+00:00'
last_modified: 2022-09-01 22:12:04.177302
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21512
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW21512
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་པ་དཀར་བརྒྱུད་པའི་དབང་དཔེ།
  author: མཁས་དབང་སངས་རྒྱས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.702383222349722
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I0842:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0842
      total_pages: 514
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0842.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.702383222349722
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
