id: IB2120205
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:42:04+00:00'
last_modified: '2022-06-08T12:37:08.668649+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21512
  title: འབྲུག་པ་དཀར་བརྒྱུད་པའི་དབང་དཔེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB85:
      image_group_id: I0842
      title: ''
      total_pages: 514
      order: 1
      base_file: FB85.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
